### PR TITLE
ARCRC new ontology terms + formatting + metadata, SALMON new run size term + formatting + metadata

### PR DESCRIPTION
**Pull request by justinkadi**
ARCRC turtle file
- Added new terms for ARCRC 2023 
- Reformat/collapse namespaces and prefixes
- Add metadata, update version

SALMON turtle file
- Added run size term for SALMON
- Reformat/collapse namespaces and prefixes
- Add metadata, update version

### CODE REVIEW

**Comment by justinkadi** [comment]
@mbjones it looks like there were some checks that failed. Are these things that I should be able to fix?

**Comment by mbjones** [comment]
@justinkadi the validate check is something you can fix -- there's a syntax problem of some sort on the indicated line of the ontology file. Should be pretty easy to track down. We don't want to do a release until the CI/validate check works.  The other failing test is the Mosiac check, which hasn't worked in a long time (I traced it down to a change in the MOSAiC service, so its not your ontology changes causing it, and you can ignore it for now (you aren't even working on the MOSAiC ontology).

**Comment by justinkadi** [comment]
@mbjones I was able to fix the CI/validate check. I noticed the CI/website was skipped, but I think it's ready for merging otherwise.

**Review by mbjones — APPROVED** [review]
Looks good to me with the syntax change.

**Pull request merged**
