### PR TITLE
Add gh-pages website for repo, MOSAiC 1.0.1, and various MOSAiC extras

### PR DESCRIPTION
**Pull request by amoeba**
This PR adds a GH Pages-built website for the entire repo, see https://dataoneorg.github.io/sem-prov-ontologies/. It's set up to only build off the main branch. See #101.

This PR also adds version 1.0.1 of the MOSAiC ontology (#104) and adds some extra features: SHACL validation (#103) and correspondence checking between PANGAEA's info and our ontology (#102).

Once merged, I'll tag a MOSAiC 1.0.1 release off of the merge commit.

### CODE REVIEW

**Comment by amoeba** [comment]
Hey @mbjones, do you want to take a look here before I merge? The MOSAiC 1.0.1 ontology and related stuff is pretty straightforward but I think the new website build is worth a look. It's super barebones and could be made a lot snazzier if we like but it's a start.

**Comment by mbjones** [comment]
Sure, I can take a look. Thoughts on why the MOSAiC correspondence check is failing with the error:

> Exception: Campaign with label 'KD-MOSAiC-1' not found in the expected set ['PS122/5', 'PS122/4', 'P5_223_MOSAiC_ACA_2020', 'PS122/1', 'PS122/2', 'PS122/3', 'AF-MOSAiC-1', 'P6_222_IceBird_MOSAiC_2020', 'AT-MOSAiC-1']

Is that expected and you're just ignoring it for now?

**Review by mbjones — APPROVED** [review]
Overall these changes look good. The basic website seems useful and a good starting point, so it is fine as is. The pyLODE pages are great with the resolvable term URIs! I looked over the changes int he OWL file and they all look fine, but it was a fairly superficial review -- I did not open it in Protege, as I think you and @mpsaloha were pretty careful with all of that so I'll leave it to you.

The only issue I saw was the lack of `owl:equivalentClass` and `owl:equivalentProperty` statements to link the new `https` URIs to the older `http` URIs. As we have already annotated datasets against the `http` URIs, what is the plan there to support the crosswalk?

I'll go ahead and mark this as approved so you can merge when ready.

**Comment by mbjones** [comment]
Oh, and also the correspondence check is failing, which seems like we should fix.

**Comment by amoeba** [comment]
> The only issue I saw was the lack of owl:equivalentClass and owl:equivalentProperty statements to link the new https URIs to the older http URIs. As we have already annotated datasets against the http URIs, what is the plan there to support the crosswalk?

When we decided to make the change, I checked in with @laijasmine to see what had already been annotated. IIRC it was only about four annotations in total and we updated the affected documents with the corrected IRIs. And all affected records were never publicly-readable. I felt this was good enough at the time and didn't want to go down the route of issuing the equivalences you mention. Does that sound good enough to you?

> Oh, and also the correspondence check is failing, which seems like we should fix.

Yep, good catch. We'll have to coordinate who'll do the work on that (we're missing a Campaign).

I'll leave this PR open until we coordinate on the equivalence issue above.

**Comment by mbjones** [comment]
Your approach to the http/https equivalence seems great given that the annotated versions were all private. So, yeah, let's go with this.

N.B.  The same http/https issue will likely arise for other ontologies that may be more used in the wild.

**Comment by amoeba** [comment]
> N.B. The same http/https issue will likely arise for other ontologies that may be more used in the wild.

Right, good point. Thanks.

**Pull request merged**
